name: TradeCraft
main: nl.armeagle.TradeCraft.TradeCraft
version: AE-1.0.0
commands:
    tc:
        help:
            description: Show TradeCradt command help
        shops:
            description: See a printout of any personal shops you have
            usage: 
        currency:
            description:  Get/set the currency used.
            usage: Enter an id with an optional data value separated by a semicolon
        reload:
            description: reload the script and with that all the configuration files
            usage:
