name: TradeCraft
main: nl.armeagle.TradeCraft.TradeCraft
version: AE-1.0.0-alpha3
commands:
    myshops:
        description: See a printout of any personal shops you have
        usage: 
    setCurrency:
        description:  Set the currency used.
        usage: Enter an id or a material name (using _ as spaces)
    displayCurrency:
        description: Check what currency is being used.
        usage: Displays the current material name of the currency used.
    canPlayer:
        description:  See what permissions a player has regarding TradeCraft
        usage: enter a user name